### ISSUE TITLE
clear()

### ISSUE THREAD

**Issue by iv41879** [waddlesplash/QMidi#10]
When clearing events (fEvents) we should also clear tempo events list and track list just by calling clear() cause when loading new song we have non-valid tempo event pointers and tracks from previous song

**Comment by waddlesplash** [comment]
clear() being public was always a bad idea. I'll probably make it private... (and make QMidiFile single-instance only)

**Comment by midi-pascal** [comment]
@waddlesplash I do not understand why a public Clear() is a bad idea.
Could you elaborate on this please?

**Comment by waddlesplash** [comment]
Because QMidiFile was mostly designed to be single-instance only.
