### ISSUE TITLE
How can i change tempo in real time playing.

### ISSUE THREAD

**Issue by pie62** [waddlesplash/QMidi#14]
I see your code in https://github.com/waddlesplash/QMidi/blob/84a2d655c35a3aced9c239949c8c08c18e548bd1/examples/qtplaysmf/playsmf.cpp#L34
and i try to change tempo (BPM) in real time playing,  But not working.
So can you recommend me how ?

**Comment by waddlesplash** [comment]
If you just want to change speed, it should be more or less easy to do that -- just apply some sort of scaling factor to the ms times. Otherwise, you'll need to modify the `Tempo` events.
