### ISSUE TITLE
QMidiFile should empty its events when loading a new file.

### ISSUE THREAD

**Issue by JosteinTopland** [waddlesplash/QMidi#2]
Events are added to any previous loaded MIDI file. Sounds a bit messy when loading a new file. How about adding fEvents.clear() in load() right before looping through the tracks, or am I missing something?

**Comment by waddlesplash** [comment]
I haven't touched most of this code in years and there are probably a lot of idiotic things in it. Personally I don't think loading another file should be possible, and I might get rid of the load() function altogether and put it in the constructor.
