### ISSUE TITLE
Upgrade QMidi to be compatible with Qt 6.2

### ISSUE THREAD

**Issue by paulmasri** [waddlesplash/QMidi#29]
I have done this and will submit a PR.

Following the [Porting to Qt 6](https://doc.qt.io/qt-6/portingguide.html) guide, I first compiled with Qt 5.15 disabling deprecated functionality. This showed that `qStableSort()` has been deprecated in favour of `std::stable_sort`.

The only other change needed is the CMakeLists.txt which is specific to Qt 5.

**Comment by waddlesplash** [comment]
Thanks!
