### ISSUE TITLE
Fails to build on FreeBSD 13.0-RELEASE

### ISSUE THREAD

**Issue by probonopd** [waddlesplash/QMidi#32]
Fails to build on FreeBSD 13.0-RELEASE:

```
FreeBSD% LANG=C cmake ..   
-- Configuring done
CMake Error: AUTOMOC for target QMidi: Could not find moc executable target Qt5::moc
CMake Generate step failed.  Build files cannot be regenerated correctly.
```

**Comment by waddlesplash** [comment]
```
LANG=C 
```
Why are you setting this?

Anyway, the problem is clearly specified: MOC couldn't be found by the AUTOMOC tool. That seems to be mostly likely an issue on the system?

**Comment by probonopd** [comment]
> Why are you setting this?

To get Englsh error messages.

Should this be working?

```
FreeBSD% moc
zsh: command not found: moc
```

I do have `/usr/local/lib/qt5/bin/moc`.

**Comment by LeStahL** [comment]
try 
```bash
export PATH=/usr/local/lib/qt5/bin:$PATH
cmake ..
```

**Comment by probonopd** [comment]
Unfortunately that's not it. Same error message. I can build other Qt projects just fine on this machine. This is what is puzzling me.

Another project:

```
FreeBSD% truss cmake .. 2>&1 | grep moc
access("/usr/local/lib/qt5/bin/moc",R_OK)        = 0 (0x0)
access("/usr/local/lib/qt5/bin/moc",R_OK)        = 0 (0x0)
fstatat(AT_FDCWD,"/usr/local/lib/qt5/bin/moc",{ mode=-rwxr-xr-x ,inode=699497,size=910800,blksize=131072 },0x0) = 0 (0x0)
```

This project:

```
FreeBSD% truss cmake .. 2>&1 | grep moc

CMake Error: AUTOMOC for target QMidi: Could not find moc executable target Qt5::mocwrite(2,"CMake Error: AUTOMOC for target "...,84) = 84 (0x54)
```

Maybe it's _something_ in the CMake files.

**Comment by LeStahL** [comment]
Looked into it - It seems to correlate with https://github.com/waddlesplash/QMidi/blob/master/CMakeLists.txt#L11.
I reproduced the problem with the version inside the repo on msvc2022

When I uncomment the line linked above, everything builds just fine.

**Comment by LeStahL** [comment]
Seems like https://github.com/waddlesplash/QMidi/pull/30/commits/ae96b4765835d5e5647a85138aa602d095847ef4 added this line commented (?) as part of #30
the line is needed tho (compare https://github.com/waddlesplash/QMidi/pull/30#discussion_r742429832)
