### ISSUE TITLE
Wrong track format check

### ISSUE THREAD

**Issue by iv41879** [waddlesplash/QMidi#5]
If midi file has wrong track format than function QMidiFile::load stucks in indefinite loop where condition is always true...
`while (number_of_tracks_read < number_of_tracks)`

Please see attached example midi file

[+Careless.zip](https://github.com/waddlesplash/QMidi/files/191503/Careless.zip)

**Comment by waddlesplash** [comment]
I'm not closing this so I can look into the unsupported track format further.

**Comment by waddlesplash** [comment]
Yeah, it appears that file is just plain corrupt, two other players I tried give errors when attempting to load it.
