### ISSUE TITLE
QMidiFile::load gets stucked when parsing attached midi file

### ISSUE THREAD

**Issue by iv41879** [waddlesplash/QMidi#7]
It creates note on events in infinite loop. Actually file is broken and is only maybe partially loaded. Can we add some safety feature just to stop further loading and play what we have up to that tick?

![qmidi-file-error](https://cloud.githubusercontent.com/assets/6260936/19374880/796c60c0-91cf-11e6-9325-f5d30b72a7a8.PNG)

[We Are The Champions.zip](https://github.com/waddlesplash/QMidi/files/528617/We.Are.The.Champions.zip)

**Comment by waddlesplash** [comment]
Anvil Studio loads the file properly, but warns that it had errors. Will investigate.

**Comment by waddlesplash** [comment]
(I probably should actually refactor this ancient code someday, there's probably a lot of other bugs like this one in it.)

**Comment by iv41879** [comment]
Thanks

**Comment by iv41879** [comment]
Actually, seems we have regression here from issue #3 .
So I restored old version of the code which now works for me - so when selecting corrupted file we had nice feature that we load events up to the place of the file damage - partial loading (same as vanBasco is doing). Now this code loads some dummy midi events. Please can you take a look.
So attached file is one that works for me now nicely.

[QMidi.zip](https://github.com/waddlesplash/QMidi/files/531150/QMidi.zip)

**Comment by waddlesplash** [comment]
Done.
