### ISSUE TITLE
Port QMidiOut to macOS (CoreMidi)

### ISSUE THREAD

**Issue by waddlesplash** [waddlesplash/QMidi#8]
I do have access to macOS, but I've no particular interest to go down the rabbit hole that is CoreMidi. If anyone else is, I'll happily accept patches...

**Comment by paulmasri** [comment]
I'm starting work on this. My plan is to make use of the third party [RtMidi](https://github.com/thestk/rtmidi) library.

**Comment by waddlesplash** [comment]
I'd really prefer to not make a third-party library a hard dependency, even if it's only on one platform. Would it be possible to implement an interface to CoreMidi directly?

**Comment by paulmasri** [comment]
For my own apps, I need MIDI support in Qt for Windows, MacOS and iOS. As QMidi is already established for Windows and I like the architecture of your library, my plan was to add in support for the other 2 platforms.

However I don't have the in-depth knowledge of CoreMidi to write this from scratch, nor the time, so my plan was to make use of RtMidi for MacOS and PGMidi for iOS, both of which are mature libraries.

If you would prefer not to use third party libraries, I respect that, and I'll do my own development independently. If you're okay with these libraries then I'd be delighted to contribute to this open source project.

**Comment by waddlesplash** [comment]
Isn't it CoreMidi on both platforms? PGMidi looks OK, is it possible to use that for macOS too? Or are the APIs really separate and just have the same name?

**Comment by paulmasri** [comment]
That's a good question. I noticed that openFrameworks MIDI plugin ofxMidi uses RtMidi for Windows & Mac and PGMidi for iOS and I had assumed the implementations would be different.

I shall find out if a single implementation will work for both and if so, which is the best one.
