### ISSUE TITLE
Time - Tick conversion

### ISSUE THREAD

**Issue by iv41879** [waddlesplash/QMidi#9]
![issue-time-tick-conversion](https://cloud.githubusercontent.com/assets/6260936/19834817/051a0454-9e70-11e6-8bf3-12a4c92b50d4.PNG)

Time conversion to tick and tick to time does not give equal values. Is this deviation ok?

**Comment by waddlesplash** [comment]
It's converting to an absolute tick value, which may not be at that precise time value, which is expected, no?

**Comment by midi-pascal** [comment]
@waddlesplash :+1: There is no tick each microsecond so the precision is dependent on fResolution.
No trouble there IMHO
